### PR TITLE
parent login/logout

### PR DESCRIPTION
**Pull request by mohit**
here:
- function to ensure protected routes
- get user from firebase after google login flow
- logout from google using firebase

not here:
- does not redirect properly
- state of user does not propogate to the appropriate pages

further:
- send the parent id to the server? maybe or 
- use relayState for sending parentid to clever auth
- UI changes.

### CODE REVIEW

**Comment by ipam73** [comment]
🚢 🚀

**Comment by mohit** [comment]
- set user state on load of app based on `firebase.auth().currentUser`
- some way to set this on the server side.

**Comment by mohit** [comment]
also added:
- Parent Id is shared with server to scope students added. 
- using relayAuth
- Parent displayName in Header.

should be ready to merge now. Next steps:
- cleanup login triggers (happening too many times right now)
- there is an issue with setting state (error in console though things seem to be working fine)
- security of the relayState needs work.

**Comment by mohit** [comment]
@ipam73 completed merge with master.

**Pull request merged**
